apiVersion: v1
kind: ReplicationController
metadata:
  name: backend-rc
spec:
  replicas: 2
  selector:
    app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: nphamvn/demo-app-backend:main
          name: backend
          ports:
            - containerPort: 8080
