on:
  push:
    branches: ["main"]
    paths: ["src/frontend/**", ".github/workflows/build-and-push-frontend.yml"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: "24.7.0"
          cache: "npm"
          cache-dependency-path: src/frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./src/frontend
        run: npm ci

      - name: Run lint
        working-directory: ./src/frontend
        run: npm run lint

      - name: Run tests
        working-directory: ./src/frontend
        run: npm test -- --watchAll=false

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout source
        uses: actions/checkout@v5.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/demo-app-frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./src/frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
