on:
  push:
    branches: ["main"]
    paths: ["src/backend/**", ".github/workflows/build-and-push-backend.yml"]
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        working-directory: ./src/backend
        run: dotnet restore

      - name: Build
        working-directory: ./src/backend
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        working-directory: ./src/backend
        run: dotnet test --no-build --configuration Release --verbosity normal

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/demo-app-backend
          tags: |
            type=semver,pattern={{version}} # Uses Git tags like v1.0.0
            type=sha,format=long # Uses long commit SHA
            type=ref,event=branch # Uses branch name

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./src/backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
